import os
import json
import boto3
from typing import Dict, List
from dotenv import load_dotenv

load_dotenv()

class VoiceAgent:
    def __init__(self):
        self.region = os.getenv("AWS_REGION", "us-east-1")
        self.polly = boto3.client("polly", region_name=self.region)
        self.voice_id = "Matthew"
        self.base_output_dir = "output"

    def generate_audio(self, script_json: Dict, reel_name: str) -> List[str]:
        generated_files = []
        scenes = script_json.get("scenes", [])
        
        audio_dir = os.path.join(self.base_output_dir, reel_name, "audio")
        os.makedirs(audio_dir, exist_ok=True)
        
        for scene in scenes:
            scene_num = scene.get("scene_number")
            
            if "voice_line" not in scene:
                raise ValueError(f"Missing voice_line field in scene {scene_num}")
                
            voice_line = scene.get("voice_line")
            
            if not voice_line or not voice_line.strip():
                continue
                
            try:
                response = self.polly.synthesize_speech(
                    Text=voice_line,
                    OutputFormat="mp3",
                    VoiceId=self.voice_id,
                    Engine="neural"
                )
                
                file_path = os.path.join(audio_dir, f"scene_{scene_num}.mp3")
                if "AudioStream" in response:
                    with open(file_path, "wb") as f:
                        f.write(response["AudioStream"].read())
                    generated_files.append(file_path)
            except Exception as e:
                print(f"Error generating audio for scene {scene_num}: {e}")
                
        return generated_files

if __name__ == "__main__":
    example_script = {
        "scenes": [
            {
                "scene_number": 1,
                "voice_line": "Welcome to the world of AI agents."
            },
            {
                "scene_number": 2,
                "voice_line": "This is a voice-over generated by Amazon Polly."
            },
            {
                "scene_number": 3,
                "voice_line": ""
            }
        ]
    }
    
    agent = VoiceAgent()
    try:
        audio_files = agent.generate_audio(example_script, "example_reel_male_Matthew")
        print(f"Generated audio files: {audio_files}")
    except ValueError as e:
        print(f"Validation Error: {e}")
