import os
import json
import boto3
from typing import Dict, List
from dotenv import load_dotenv

load_dotenv()

class VoiceAgent:
    def __init__(self, voice_id: str = "Justin", engine: str = "neural"):
        self.region = os.getenv("AWS_REGION", "us-east-1")
        self.polly = boto3.client("polly", region_name=self.region)
        self.voice_id = voice_id
        self.engine = engine
        self.base_output_dir = "output"

    def generate_speech_marks(self, text: str, text_type: str = "text") -> str:
        """
        Calls Amazon Polly to generate word-level speech marks for the given text.
        """
        try:
            response = self.polly.synthesize_speech(
                Text=text,
                OutputFormat="json",
                VoiceId=self.voice_id,
                Engine=self.engine,
                TextType=text_type,
                SpeechMarkTypes=["word"]
            )
            
            if "AudioStream" in response:
                return response["AudioStream"].read().decode("utf-8")
        except Exception as e:
            print(f"Error generating speech marks: {e}")
        return ""

    def generate_audio(self, script_json: Dict, reel_name: str, mode: str = "story") -> List[str]:
        generated_files = []
        scenes = script_json.get("scenes", [])
        
        audio_dir = os.path.join(self.base_output_dir, reel_name, "audio")
        os.makedirs(audio_dir, exist_ok=True)
        
        for scene in scenes:
            scene_num = scene.get("scene_number")
            
            if "voice_line" not in scene:
                raise ValueError(f"Missing voice_line field in scene {scene_num}")
                
            voice_line = scene.get("voice_line")
            
            if not voice_line or not voice_line.strip():
                continue
                
            try:
                text_to_synthesize = voice_line
                text_type = "text"
                
                if mode == "news":
                    # Use SSML for news mode to ensure a slower, professional pace
                    text_to_synthesize = f"<speak><prosody rate='slow'>{voice_line}</prosody></speak>"
                    text_type = "ssml"

                response = self.polly.synthesize_speech(
                    Text=text_to_synthesize,
                    OutputFormat="mp3",
                    VoiceId=self.voice_id,
                    Engine=self.engine,
                    TextType=text_type
                )
                
                file_path = os.path.join(audio_dir, f"scene_{scene_num}.mp3")
                if "AudioStream" in response:
                    with open(file_path, "wb") as f:
                        f.write(response["AudioStream"].read())
                    
                    # Generate and save speech marks
                    speech_marks = self.generate_speech_marks(text_to_synthesize, text_type)
                    if speech_marks:
                        speechmarks_path = f"{file_path}_speechmarks.json"
                        with open(speechmarks_path, "w") as f:
                            f.write(speech_marks)
                    
                    generated_files.append(file_path)
            except Exception as e:
                print(f"Error generating audio for scene {scene_num}: {e}")
                
        return generated_files

if __name__ == "__main__":
    example_script = {
        "scenes": [
            {
                "scene_number": 1,
                "voice_line": "Welcome to the world of AI agents."
            },
            {
                "scene_number": 2,
                "voice_line": "This is a voice-over generated by Amazon Polly."
            },
            {
                "scene_number": 3,
                "voice_line": ""
            }
        ]
    }
    
    agent = VoiceAgent()
    try:
        audio_files = agent.generate_audio(example_script, "example_reel_male_Matthew")
        print(f"Generated audio files: {audio_files}")
    except ValueError as e:
        print(f"Validation Error: {e}")
